### ISSUE TITLE
Support HD wallets

### ISSUE THREAD

**Issue by kamikazechaser** [grassrootseconomics/mySarafu#17]
Steps:

- generate mnemonic with bip 39
- generate seed from above mnemonic (bip39.mnemonicToSeedHex)
- encrypt mnemonic and store locally and remotely

Then:

- Load seed hex everytime
- Check hd wallet range stored locally and load all derived keys

**Comment by williamluke4** [comment]
https://pub.dev/packages/dart_bip32_bip44
